#!/bin/bash
# Set As Wallpaper
    pkexec convert -resize 1920 -quality 100 -brightness-contrast -10x-15 -blur 0x30 $HOME/.cache/wallpaper/* /usr/share/backgrounds/bg-boat.jpg
sleep 3
    gsettings set org.gnome.desktop.screensaver picture-uri "file:///usr/share/backgrounds/bg-boat.jpg"
# Enjoy!
exit 1
